### ISSUE TITLE
Exceptions being thrown when attempting to update existing tags.

### ISSUE THREAD

**Issue by 1832923** [kotcrab/szurubooru-auto-tagger#11]
### I have a local server set up running Szurubooru using Docker and am trying to run this on a separate Windows 10 machine. I am attemping to update existing tags to get their categories automatically. When attempting to use Danbooru authenticated I get the following error (everything in square brackets has been redacted):

**PS C:\Users\\[W10user]\Downloads\szurubooru-auto-tagger-1.2\bin> .\szurubooru-auto-tagger -t ExistingTags**
Szurubooru auto tagger
Using config from C:\Users\\[W10user]\Downloads\szurubooru-auto-tagger-1.2\lib\config.yaml
Exception in thread "main" javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:563)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:540)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:227)
        at com.kotcrab.szurubooru.tagger.RestClient.executeSafely(RestClient.kt:71)
        at com.kotcrab.szurubooru.tagger.RestClient.get(RestClient.kt:37)
        at com.kotcrab.szurubooru.tagger.RestClient.get$default(RestClient.kt:36)
        at com.kotcrab.szurubooru.tagger.Danbooru.getPost(Danbooru.kt:70)
        at com.kotcrab.szurubooru.tagger.Danbooru.isAuthorized(Danbooru.kt:40)
        at com.kotcrab.szurubooru.tagger.AutoTagger.<init>(AutoTagger.kt:59)
        at com.kotcrab.szurubooru.tagger.MainKt.main(Main.kt:55)

### Looking at that I figured I would give it a shot unauthenticated and here is what I got from that:

**PS C:\Users\\[W10user]\Downloads\szurubooru-auto-tagger-1.2\bin> .\szurubooru-auto-tagger -t ExistingTags**
Szurubooru auto tagger
Using config from C:\Users\\[W10user]\Downloads\szurubooru-auto-tagger-1.2\lib\config.yaml
Booru connectivity looks ok
Reading tag map...
Obtaining tags.json...
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.kotcrab.szurubooru.tagger.RestClient.get(RestClient.kt:37)
        at com.kotcrab.szurubooru.tagger.RestClient.get$default(RestClient.kt:36)
        at com.kotcrab.szurubooru.tagger.Szurubooru.getTags(Szurubooru.kt:54)
        at com.kotcrab.szurubooru.tagger.AutoTagger.<init>(AutoTagger.kt:69)
        at com.kotcrab.szurubooru.tagger.MainKt.main(Main.kt:55)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1567)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1416)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
        at com.google.gson.JsonParser.parse(JsonParser.java:60)
        ... 6 more

### Here is my config.yaml (indentationlooks weird here, but it is correct in the file):

triggerTag: auto_tagme
managedTag:
errorTag: auto_tagger_error
noMatchTag: tagme
batchUploadTag: auto_tagme

checkBooruConnectivity: true
storeSourceUrl: false
updateImageRating: true
updateImageNotes: true
createCommentWhenBiggerImageFound: true

singleInstance:
  enabled: true
  port: 54212

tags:
  obtainAliases: true
  obtainSuggestions: false
  obtainImplications: true
  tagMapFile: tagMap.yaml
  tagEscaping:
    escapeCharacters: '/+'
    escapeWith: _

  remapCategories:
    - from: general
      to: default
    - from: artist
      to: creator
    - from: character
      to: hero
    - from: copyright
      to: series

szurubooru:
  apiPath: http://192.168.1.129:6666
  dataPath: http://192.168.1.129:8121
  username: auto-tagger
  password: auto-tagger

danbooru:
  anonymous: false
  username: [username]
  apiKey: [API key]
  hourRequestLimit: 3000

**Comment by kotcrab** [comment]
There was a breaking change made in szurubooru, It's probably fixed in [this fork](https://github.com/Krazer89/szurubooru-auto-tagger). 
I haven't touched this project in a long while but maybe I'll come back to it.

**Comment by kotcrab** [comment]
I've copied the changes from that fork which should fix this. That said though I'll be rewriting this project soon which will likely be a breaking change.

**Comment by 1832923** [comment]
Thank you for looking into it for me. I built the jar with the updates and I still get the same error when trying to use danbooru authed, but now unauthed its giving me the following:

Exception in thread "main" java.lang.ClassCastException: java.util.HashMap cannot be cast to com.kotcrab.szurubooru.tagger.RemapDto
        at com.kotcrab.szurubooru.tagger.AutoTagger.remapTagCategory(AutoTagger.kt:557)
        at com.kotcrab.szurubooru.tagger.AutoTagger.<init>(AutoTagger.kt:73)
        at com.kotcrab.szurubooru.tagger.MainKt.main(Main.kt:55)

I tired to make sense of it, but I just don't know anything about Kotlin. If this isn't a trivial problem I wouldn't worry about it since you are planning on rewriting anyway.

**Comment by kotcrab** [comment]
You should remove `remapCategories` section from the config. It's not deserialized correctly (it's a bug in auto-tagger).

**Comment by 1832923** [comment]
Well, that did help getting further into the program, but now I get the SSLHandshakeException upon every iteration going through the tags, even when I have anonymous set to true in the conifg. I even tried to manually add the danbooru cert into java but that didn't help either.

**Comment by kotcrab** [comment]
I'd need to see the full stack trace but I just noticed in your first comment you're getting `SSLHandshakeException` in the `Danbooru.isAuthorized` this is weird. Even with wrong credentials you would get error 401. This suggests something is wrong with your Java installation / certificate store. Try using OpenJDK 11 from https://adoptopenjdk.net/ (I know readme calls for Java 8 - it's old...)

**Comment by 1832923** [comment]
OpenJDK did it, everything seems to be working now. Thank you so much for the help!

**Comment by kotcrab** [comment]
Great, I've updated the readme. I'm closing this, the issue with categories remap will be addressed in the rewrite.
